# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a32bf7488567bfaeace09a3382b018bfb033072f1ae7dd59cf8376727139aad65a6e53383e87b31449f52ea963d9128250d369167e395578ac732c54ba4d2499

test:
  secret_key_base: a85ceba0812e8dc83a0806a0c7629d109997bb8312faff2fd30db3eaaa46e5c82f413a56c4ffc35301d69d808dead63999365c1ed6614ca40502b25b2be70e60

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
